/** Auto-generated by `pnpm tunnel`. Do not edit by hand.
 *  When the tunnel is running, this file is rewritten with the tunnel's
 *  service DID + URL; when the tunnel stops, it is reset to null values. */

export const SERVICE_DID: string | null = "did:web:providers-exchange-gbp-combinations.trycloudflare.com";
export const SERVICE_URL: string | null = "https://providers-exchange-gbp-combinations.trycloudflare.com";
